# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('prefix', models.CharField(max_length=7)),
                ('template', models.CharField(max_length=25)),
                ('active', models.NullBooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
