# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='minter',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='ark',
            name='minter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkapp.Minter'),
        ),
    ]
